// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartBus_BusinessObjects.Models;

public partial class BusRoute
{
    public string Id { get; set; }

    public string RouteCode { get; set; }

    public string RouteName { get; set; }

    public decimal? DistanceKm { get; set; }

    public string BusType { get; set; }

    public TimeOnly? StartTime { get; set; }

    public TimeOnly? EndTime { get; set; }

    public int? TripsPerDay { get; set; }

    public int? TripDuration { get; set; }

    public string TripInterval { get; set; }

    public string PathToDestination { get; set; }

    public string PathToStart { get; set; }

    public virtual ICollection<BusVehicleLocation> BusVehicleLocations { get; set; } = new List<BusVehicleLocation>();

    public virtual ICollection<RouteSchedule> RouteSchedules { get; set; } = new List<RouteSchedule>();

    public virtual ICollection<RouteStop> RouteStops { get; set; } = new List<RouteStop>();

    public virtual ICollection<RouteTicketPrice> RouteTicketPrices { get; set; } = new List<RouteTicketPrice>();

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}