// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartBus_BusinessObjects.Models;

public partial class BusVehicleLocation
{
    public int VehicleId { get; set; }

    public string RouteId { get; set; }

    public double? Latitude { get; set; }

    public double? Longitude { get; set; }

    public double? Speed { get; set; }

    public DateTime? LastUpdated { get; set; }

    public virtual BusRoute Route { get; set; }
}