// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartBus_BusinessObjects.Models;

public partial class PaymentOrder
{
    public int Id { get; set; }

    public long OrderCode { get; set; }

    public string Status { get; set; }

    public string TicketRequestJson { get; set; }

    public DateTime CreatedDate { get; set; }
}