// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartBus_BusinessObjects.Models;

public partial class RouteTicketPrice
{
    public int Id { get; set; }

    public string RouteId { get; set; }

    public int? TicketTypeId { get; set; }

    public decimal? Price { get; set; }

    public string TicketName { get; set; }

    public virtual BusRoute Route { get; set; }

    public virtual TicketType TicketType { get; set; }
}