// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartBus_BusinessObjects.Models;

public partial class RouteStop
{
    public int Id { get; set; }

    public string RouteId { get; set; }

    public int? StopId { get; set; }

    public virtual BusRoute Route { get; set; }

    public virtual BusStop Stop { get; set; }
}