// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartBus_BusinessObjects.Models;

public partial class Ticket
{
    public int Id { get; set; }

    public int? UserId { get; set; }

    public string RouteId { get; set; }

    public int? TicketTypeId { get; set; }

    public string Qrcode { get; set; }

    public DateTime? IssuedAt { get; set; }

    public DateTime? ExpiredAt { get; set; }

    public int? RemainingUses { get; set; }

    public bool? IsActive { get; set; }

    public decimal? Price { get; set; }

    public virtual BusRoute Route { get; set; }

    public virtual TicketType TicketType { get; set; }

    public virtual ICollection<TicketUsageLog> TicketUsageLogs { get; set; } = new List<TicketUsageLog>();

    public virtual User User { get; set; }
}