// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartBus_BusinessObjects.Models;

public partial class TicketUsageLog
{
    public int Id { get; set; }

    public int? TicketId { get; set; }

    public DateTime? ScannedAt { get; set; }

    public string ScannedBy { get; set; }

    public string Location { get; set; }

    public bool? IsValidScan { get; set; }

    public virtual Ticket Ticket { get; set; }
}