// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartBus_BusinessObjects.Models;

public partial class TicketType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int? DurationDays { get; set; }

    public int? MaxUses { get; set; }

    public bool? IsUnlimited { get; set; }

    public virtual ICollection<RouteTicketPrice> RouteTicketPrices { get; set; } = new List<RouteTicketPrice>();

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}