name: Keep Render Alive

on:
  schedule:
    - cron: "*/5 * * * *" # chạy mỗi 5 phút
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render API
        run: |
          curl -s https://smartbus-68ae.onrender.com/ > /dev/null
