name: Keep Render Alive

on:
  schedule:
    - cron: "*/5 * * * *"   # chạy mỗi 5 phút
  workflow_dispatch:        # có thể chạy thủ công nếu muốn

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping health endpoint
        run: |
          echo "Pinging https://smartbus-68ae.onrender.com/health"
          curl -fsS --max-time 10 https://smartbus-68ae.onrender.com/health || true
